name: test

on:
  push:
    paths:
      - 'Makefile'
      - 'usr/**'
  pull_request:
    paths:
      - 'Makefile'
      - 'usr/**'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v3
      - run: ls -l
